export default {
    COOKIES: "COOKIES",
    SEMDATA: "SEMDATA",
    SHOWATTENDANCE: "SHOWATTENDANCE",
    SUBJECTATTENDANCE: "SUBJECTATTENDANCE",
    PROFILEDATA: "PROFILEDATA",
    USER_IMAGE: "https://ibb.co/MfRwWgJ",
    CTDATA: "CTDATA",
    THEORY_LESSON_DATA: "THEORY_LESSON_DATA",
    TUTORIAL_LESSON_DATA: "TUTORIAL_LESSON_DATA",
    THEME_PREFERENCE: "THEME_PREFERENCE",    //MobiLight or MobiDark
    THEME_MODE: 'THEME_MODE',                //ligh mode or dark mode
    GRIEVANCE_DATA: 'GRIEVANCE_DATA',
    FCM: 'FCM',
    NOTIFICATION_DATA: 'NOTIFICATION_DATA',
    NEW_NOTIFICATION: 'NEW_NOTIFICATION',
    SEM_COMMENCEMENT: 'SEM_COMMENCEMENT',
    PASSWORD_DATA: 'PASSWORD_DATA',
    SAVED_CREDENTIALS: 'SAVED_CREDENTIALS',
    TILE_PER_ROW: 'TILE_PER_ROW',
}